FROM python:3.12-slim

WORKDIR /app

COPY ../requirements_train.txt .
RUN pip install --no-cache-dir -r requirements_train.txt

COPY . /app/src

# CMD ["bash", "-c", "python src/preprocessing.py && python src/train.py"]
