FROM python:3.12-slim

WORKDIR /app

COPY requirements_train.txt /app/
RUN pip install --no-cache-dir -r /app/requirements_train.txt

COPY src/train.py /app/src/

COPY clean_data/ /app/clean_data/

RUN mkdir -p /app/model/svm /app/model/nb /app/report_site

CMD ["python", "/app/src/train.py"]


# FROM python:3.12-slim

# WORKDIR /app

# COPY ../requirements_train.txt .
# RUN pip install --no-cache-dir -r requirements_train.txt

# COPY . /app

# CMD ["bash", "-c", " python src/train.py"]
