FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY src/preprocessing.py /app/src/

COPY raw_data/ /app/raw_data/

RUN mkdir -p /app/clean_data

CMD ["python", "/app/src/preprocessing.py"]

# FROM python:3.12-slim

# WORKDIR /app

# COPY ../requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# COPY . /app

# # CMD ["bash", "-c", "python src/preprocessing.py"]

