FROM python:3.12-slim

WORKDIR /app

COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements`.txt

COPY . /app/src

# CMD ["bash", "-c", "python src/preprocessing.py && python src/train.py"]
