name: ML Pipeline with Report Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run preprocessing
        run: python src/preprocessing.py

      - name: Upload clean_data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: clean_data
          path: clean_data/

  train:
    runs-on: ubuntu-latest
    needs: preprocess
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download clean_data artifact
        uses: actions/download-artifact@v4
        with:
          name: clean_data
          path: clean_data/

      - name: Run training
        run: python src/train.py

      - name: Upload report for deploy
        uses: actions/upload-artifact@v4
        with:
          name: report_site
          path: report_site/   # folder berisi index.html, style.css, dll

  deploy:
    runs-on: ubuntu-latest
    needs: train
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: report_site
          path: ./report_site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./report_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
