name: Run Preprocessing & Train

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Preprocessing script
        run: |
          python src/preprocessing.py

      - name: Run Train models 
        run: |
          python src/train.py
          
      - name: Commit & push reports/models
        run: |
          git config --global user.name "afsra.v.arsipan.7@gmail.com"
          git config --global user.email "afsravarsipan7"
          git add .
          git diff --cached --quiet || git commit -m "Update model reports via GitHub Actions"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/hensomxxxpipel/ML-with-Github-Action.git
